### ISSUE TITLE
corejs needs updating

### ISSUE THREAD

**Issue by bendehghan** [dumbmatter/realistic-structured-clone#11]
hi there!

`npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
`
I'm getting it as part of install of another package for which your code is a requirement. 

Thanks,
Ben

**Comment by duanehutchins** [comment]
Opened a PR to fix this issue: https://github.com/dumbmatter/realistic-structured-clone/pull/12

**Comment by dumbmatter** [comment]
Thanks, but I'm not sure this is worth doing. Despite the dramatic warning message, I doubt the very minimal usage of an old version of core-js is causing any problems. And this whole package is kind of deprecated since modern environments already include `structuredClone`.

And I am kind of rubbed the wrong way by people who pollute our consoles with tons of useless information. Like oh, an old version of an npm package might not be as good as a new version? I never would have guessed! Maybe all us package maintainers should add a message like that for every old version of every package :)

**Comment by zloirock** [comment]
You are mistaken. A little subset, one of many cases, of this issue is described [here](https://www.tines.com/blog/understanding-why-our-build-got-15x-slower-with-webpack-5). I have always been amazed by people who simply do not believe in what the developers of the tools they use tell them - sure, they know all better -)

However, yes, this package is deprecated at least because [`core-js` provide `structuredClone` polyfill by itself](https://github.com/zloirock/core-js#structuredclone).

**Comment by dumbmatter** [comment]
Thanks, I will keep that in mind when applying a fix if anyone ever has a problem with this package besides npm console spam.

And it's good that other people have made structuredClone polyfills - the more the merrier. If any had existed back in 2015, realistic-structured-clone would not exist.

**Comment by zloirock** [comment]
It bacame the standard only in 2021, so previously it didn't make sense as a polyfill.

**Comment by zloirock** [comment]
> Thanks, I will keep that in mind when applying a fix if anyone ever has a problem with this package besides npm console spam.

So, you wanna going to continue to deoptimize the code and ignore notification? -) The most of users just will not understand why their apps works slower.

**Comment by dumbmatter** [comment]
My bad, I should have said "implementation" not "polyfill".

I'm not aware there is an actual performance problem. If there is a problem and someone shows me an example, I'll fix it.

**Comment by zloirock** [comment]
The example and the reason of this problem is describe [in the article](https://www.tines.com/blog/understanding-why-our-build-got-15x-slower-with-webpack-5) that was posted above. Some other V8 whims / deoptimizations mentioned [here](https://github.com/zloirock/core-js/issues/679), some other you could find in other commits / issues. Those features detection is used not only in polyfills of those features - they are used in most of `core-js` internals, so the simples way to fix it is just update `core-js` to the actual version.

**Comment by duanehutchins** [comment]
@dumbmatter I agree that polluting the console is the wrong way to go. That said, is there any harm in merging in my MR? I've already done the legwork, and it would be a shame to let it go to waste.

**Comment by dumbmatter** [comment]
v2.0.4 upgrades core-js - thanks @duanehutchins 

v3.0.0 removes core-js
